version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor: android/android
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run:
          command: ./gradlew build